from configparser import ConfigParser
import constant.constant_properties as cteProperties

parser = ConfigParser()
parser.read(cteProperties.PATH_FILE_INI_PROPERTIES)

INFLUXDB_HOST = parser.get('INFLUXDB', 'HOST')
INFLUXDB_PORT = parser.get('INFLUXDB', 'PORT')
INFLUXDB_DATABASE_NAME = parser.get('INFLUXDB', 'NAME_DATABASE_INFLUX')

PATH_OXYGEN_METRICS = parser.get('OXYGEN_METRICS','PATH_OXYGEN_METRICS')
FILENAME_METRICS_OXYGEN_RAW = parser.get('OXYGEN_METRICS','FILENAME_METRICS_OXYGEN_RAW')


PATH_TEMPERATURE_METRICS = parser.get('TEMPERATURE_METRICS','PATH_TEMPERATURE_METRICS')
FILENAME_METRICS_TEMPERATURE_RAW = parser.get('TEMPERATURE_METRICS','FILENAME_METRICS_TEMPERATURE_RAW')


PATH_HUMIDITY_METRICS = parser.get('HUMIDITY_METRICS','PATH_HUMIDITY_METRICS')
FILENAME_METRICS_HUMIDITY_RAW = parser.get('HUMIDITY_METRICS','FILENAME_METRICS_HUMIDITY_RAW')


PATH_TRANS_METRICS = parser.get('TRANSFORM_METRICS','PATH_TRANSFORM_METRICS')
FILENAME_METRICS_TRANS = parser.get('TRANSFORM_METRICS', 'FILENAME_METRICS_TRANS')

PATH_GOLD_METRICS = parser.get('GOLD_METRICS','PATH_GOLD_METRICS')
FILENAME_METRICS_GOLD = parser.get('GOLD_METRICS', 'FILENAME_METRICS_GOLD')