
FROM arm32v7/python:3.7.10-buster

COPY requirements.txt /tmp
RUN pip install -r /tmp/requirements.txt

RUN mkdir -p /data
RUN mkdir -p /app
COPY . /app/
WORKDIR /app
ENV FLASK_APP=entrypoints/app.py FLASK_DEBUG=1 PYTHONUNBUFFERED=1 FILE_CONFIG_PATH=.
CMD flask run --host=0.0.0.0 --port=80
